# Generated by Django 4.2.7 on 2023-11-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spw_id', models.IntegerField()),
                ('type_etablissement', models.CharField(max_length=255)),
                ('implementation', models.CharField(max_length=255)),
                ('nom_etablissement', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
