# Generated by Django 4.2.7 on 2023-11-27 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
